/**
 * Itinerary UI copy — re-exports from @nauta/shared (server-side).
 */
import {
  ITINERARY_PROPOSAL_CHAT_SHORT,
  ITINERARY_ACCORDION_TITLE,
  PREFERENCES_ACCORDION_TITLE,
  PREFERENCES_ACCORDION_PAYOFF,
  PREFERENCE_PANELS_CHAT_MESSAGE,
  PREFERENCE_PANELS_HINT_MESSAGE,
  ITINERARY_PROPOSAL_CHAT_MESSAGE,
  DISCOVER_ITINERARY_LABEL,
  formatUserEchoAbovePanels,
} from '@nauta/shared/itineraryCopy';

export {
  ITINERARY_PROPOSAL_CHAT_SHORT,
  ITINERARY_ACCORDION_TITLE,
  PREFERENCES_ACCORDION_TITLE,
  PREFERENCES_ACCORDION_PAYOFF,
  PREFERENCE_PANELS_CHAT_MESSAGE,
  PREFERENCE_PANELS_HINT_MESSAGE,
  ITINERARY_PROPOSAL_CHAT_MESSAGE,
  DISCOVER_ITINERARY_LABEL,
  formatUserEchoAbovePanels,
};

export const STOP_PHOTOS_ACCORDION_LABEL = 'Ecco alcune foto…';
export const ITINERARY_PANEL_CAPTION = '';
export const ITINERARY_BELOW_PANELS_MESSAGE = PREFERENCES_ACCORDION_PAYOFF;
export const TRAVEL_PLAN_PROPOSAL_MESSAGE = PREFERENCES_ACCORDION_PAYOFF;

/** Optimizer motivation line (Italy engine). */
export function buildItineraryMotivation() {
  return '';
}
